#ifndef GLOBALS_H
#define GLOBALS_H

#define FRONT_LEFT_MOT_PIN1 2
#define FRONT_LEFT_MOT_PIN2 3
#define FRONT_LEFT_MOT_PIN3 4
#define FRONT_LEFT_MOT_PIN4 5

#define BACK_LEFT_MOT_PIN1 8
#define BACK_LEFT_MOT_PIN2 9
#define BACK_LEFT_MOT_PIN3 10
#define BACK_LEFT_MOT_PIN4 11

#define FRONT_RIGHT_MOT_PIN1 40
#define FRONT_RIGHT_MOT_PIN2 41
#define FRONT_RIGHT_MOT_PIN3 42
#define FRONT_RIGHT_MOT_PIN4 43

#define BACK_RIGHT_MOT_PIN1 50
#define BACK_RIGHT_MOT_PIN2 51
#define BACK_RIGHT_MOT_PIN3 52
#define BACK_RIGHT_MOT_PIN4 53


#endif